# Generated by Django 4.1.2 on 2022-10-20 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(choices=[('m', 'Morning'), ('a', 'Afternoon'), ('e', 'Evening')], max_length=120)),
                ('d_date', models.DateField(max_length=120)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('book_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_by', to='utils.bookby')),
                ('passengers', models.ManyToManyField(blank=True, null=True, related_name='passenger', to='utils.passengerinfo')),
            ],
        ),
    ]
