# Generated by Django 3.2.11 on 2022-10-24 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_date', models.DateField(max_length=120)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('book_by', models.ForeignKey(help_text="Clik on 'plus' button to add a new 'book by'.", on_delete=django.db.models.deletion.CASCADE, related_name='book_by', to='utils.bookby')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_bus', to='utils.buse')),
                ('passengers', models.ManyToManyField(blank=True, help_text="Click on the 'plus' button to add a passenger !", null=True, related_name='passenger', to='utils.PassengerInfo')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_session', to='utils.session')),
            ],
        ),
    ]
