# Generated by Django 3.2.11 on 2022-10-24 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('contact', models.CharField(max_length=120)),
                ('address', models.TextField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Early Morning / Morning / Mid-Day / Evening / etc', max_length=120)),
                ('time', models.TimeField(help_text='HH:MM:SS')),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the town ! Required.', max_length=120)),
                ('desc', models.TextField(blank=True, help_text='Bus stops or any ! Not Required.', null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Full Name')),
                ('phone', models.CharField(max_length=13, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, help_text='Not Required !', max_length=120, null=True, verbose_name='Email')),
                ('purpose', models.CharField(max_length=120, verbose_name='Main Purpose / Issue')),
                ('details', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_from', to='utils.town')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_to', to='utils.town')),
            ],
        ),
        migrations.CreateModel(
            name='PassengerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('age', models.SmallIntegerField()),
                ('contact', models.CharField(max_length=13)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Others')], max_length=120)),
                ('seat', models.SmallIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_route', to='utils.route')),
            ],
        ),
        migrations.CreateModel(
            name='Buse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=120)),
                ('driver_contact', models.CharField(max_length=13)),
                ('bus_number', models.CharField(max_length=50)),
                ('seats', models.SmallIntegerField(help_text='Number of seats/passenger this bus can take')),
                ('d_date', models.DateField(max_length=120)),
                ('date', models.DateTimeField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_route', to='utils.route')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_session', to='utils.session')),
            ],
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('origin', 'to'), name='unique route'),
        ),
        migrations.AddConstraint(
            model_name='buse',
            constraint=models.UniqueConstraint(fields=('bus_number', 'd_date'), name='unique bus_number'),
        ),
    ]
