# Generated by Django 3.2.11 on 2022-10-24 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
